/* ============================================================================
 * AUTO-GENERATED BY tools/sim/brute_tune.py — DO NOT HAND-EDIT
 * ============================================================================
 *
 * This header is the contract between the offline Python brute-force tuner
 * and the on-MCU minimal balance application. The tuner runs a chassis
 * simulation, searches Kp/Ki/Kd by exhaustive scan against an objective
 * (settling time, overshoot, control effort), and rewrites THIS FILE with
 * the winning constants. The build then flashes them to the Uno.
 *
 * Workflow:
 *   1. cd auto_orientation/tools/sim && python3 brute_tune.py
 *   2. pio run -e arduino_uno_minimal
 *   3. pio run -e arduino_uno_minimal -t upload
 *   4. bench-test, iterate
 *
 * Defaults below come from the working reference sketch:
 *   docs/archive/balancing_robot_reference/SelfBallancingRobot3.ino
 * That sketch was hand-tuned on a Mega + BNO055 + L298N + 2× DC motors and
 * holds its balance — they are a known-decent starting point if the tuner
 * has never been run.
 *
 * Hardware assumptions baked into these values:
 *   - IMU: BNO055 in NDOF fusion mode at I2C 0x28, ~100 Hz internal rate
 *   - Motors: small DC + L298N, ~6-9 V supply, hobby gearbox
 *   - PWM range: ±255 (8-bit analogWrite)
 *   - PID sample period: 5 ms (200 Hz, via MsTimer2)
 *
 * Re-tune when ANY of these change:
 *   - Battery voltage shifts more than ~15%
 *   - Wheels, gearbox, or motors swapped
 *   - Chassis mass redistributed (mounting the IMU higher/lower changes Kd)
 *   - Tether attached/detached (the cable acts as a spring + damper)
 */

#ifndef BALANCE_CONSTANTS_H
#define BALANCE_CONSTANTS_H

#include <stdint.h>

// ----------------------------------------------------------------------------
// PID gains
// ----------------------------------------------------------------------------
// Reference .ino values (hand-tuned, Mega + BNO055 + L298N):
//   Kp = 65, Ki = 12, Kd = 38
static const float BALANCE_KP = 65.0f;
static const float BALANCE_KI = 12.0f;
static const float BALANCE_KD = 38.0f;

// ----------------------------------------------------------------------------
// Mounting offset
// ----------------------------------------------------------------------------
// Operator-measured mechanical balance angle, in degrees of pitch. The PID
// drives (raw_pitch - PITCH_OFFSET) toward zero. Reference .ino used -8.6°.
// Re-measure when the IMU is remounted or the chassis is rebuilt.
static const float PITCH_OFFSET_DEG = -8.6f;

// ----------------------------------------------------------------------------
// Loop timing
// ----------------------------------------------------------------------------
// 5 ms = 200 Hz, matches the reference .ino's PID.SetSampleTime(5).
static const uint16_t PID_SAMPLE_MS = 5;

// ----------------------------------------------------------------------------
// Output limits & stiction
// ----------------------------------------------------------------------------
// 8-bit PWM range.
static const int16_t PWM_MIN = -255;
static const int16_t PWM_MAX =  255;

// Below this PWM magnitude the motors hum but do not turn. Reference .ino
// snapped sub-threshold outputs up to ±15. Set to 0 to disable.
static const uint8_t STICTION_PWM = 15;

// ----------------------------------------------------------------------------
// Safety
// ----------------------------------------------------------------------------
// If |corrected_pitch| exceeds this, the bot is considered tipped over; motors
// are stopped and the loop refuses to drive them until pitch returns within
// the threshold (no sticky FALLEN state — simpler is better here).
static const float TIP_CUTOFF_DEG = 25.0f;

// Sanity-reject any raw pitch reading whose magnitude exceeds this. Matches
// the reference .ino's `abs(rawPitch) < 90` guard against gimbal-lock / NaN.
static const float PITCH_SANITY_DEG = 90.0f;

#endif  // BALANCE_CONSTANTS_H
